name       : google-api-python-client
version    : 1.12.8
release    : 6
source     :
    - https://github.com/googleapis/google-api-python-client/archive/v1.12.8.tar.gz : feab1360f0f2fcf8c2f92e02f7a3d16bcbeab11a3eaaae4e515d66196f9b8dd7
license    : Apache-2.0
component  : programming.python
summary    : Google APIs Python Client
description: |
    Google APIs Client Library for Python
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-google-auth-httplib2
    - python-six
    - python-uritemplate
build      : |
    %python3_setup
install    : |
    %python3_install
