name       : google-api-python-client
version    : 2.48.0
release    : 8
source     :
    - https://github.com/googleapis/google-api-python-client/archive/refs/tags/v2.48.0.tar.gz : 720236b6a383d5c56ac733ebf05891fe63eb7a9006e45144be6ea75a5cb8e080
license    : Apache-2.0
component  : programming.python
summary    : Google APIs Python Client
description: |
    Google APIs Client Library for Python
builddeps  :
    - python-setuptools
rundeps    :
    - python-google-api-core
    - python-google-auth-httplib2
    - python-uritemplate
build      : |
    %python3_setup
install    : |
    %python3_install
