name       : google-api-python-client
version    : 1.7.7
release    : 2
source     :
    - https://files.pythonhosted.org/packages/e0/91/0e6a42ea3e0898a75d819a9690c8c8d0eecd31275d8a85503c8fc33949f2/google-api-python-client-1.7.7.tar.gz : 9106e7d09d80f59a9472a91edd85c2d6ad420aef28c9440ce1691b4a19ba9ada
license    : Apache-2.0
component  : programming.python
summary    : Google APIs Python Client
description: |
    Google APIs Client Library for Python
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-httplib2
    - python-six
    - python-uritemplate
build      : |
    %python3_setup
install    : |
    %python3_install
