name       : google-api-python-client
version    : 1.7.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/5e/48/68c64f848b7beaa49bfaa98c3436f34b40a244ab96e8afec3926ac024a19/google-api-python-client-1.7.3.tar.gz : e32d30563b90c4f88ff042d4d891b5e8ed1f6cdca0adab95e9c2ce2603087436
license    : Apache-2.0
component  : programming.python
summary    : Google APIs Python Client
description: |
    Google APIs Client Library for Python
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-httplib2
    - python-six
    - python-uritemplate
build      : |
    %python3_setup
install    : |
    %python3_install