name       : google-api-python-client
version    : 1.7.8
release    : 3
source     :
    - https://files.pythonhosted.org/packages/7a/84/ffde3c95d4162cdc8bae710fecc6873cccb05ac33afc3b2c925c74cc0150/google-api-python-client-1.7.8.tar.gz : 06907006ed5ce831018f03af3852d739c0b2489cdacfda6971bcc2075c762858
license    : Apache-2.0
component  : programming.python
summary    : Google APIs Python Client
description: |
    Google APIs Client Library for Python
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-httplib2
    - python-six
    - python-uritemplate
build      : |
    %python3_setup
install    : |
    %python3_install
